[package]
name = "gild"
version = "0.1.1"
authors = ["Nickforall <hello@nickforall.nl>"]
description = "A simple validator library"
license = "MIT"
repository = "https://github.com/Nickforall/Gild"

[dependencies]
regex = "0.2"
lazy_static = "0.2"
